sudo: required
language: python
python:
  - "2.7"
# command to install dependencies
install: "sudo pip install tox && mkdir -p vendor/ && pip install --download vendor/ -r requirements-normal.txt && pip install --download vendor/ -r requirements-native.txt --no-use-wheel"
# command to run tests
script: tox
